"""LLM-backed post-processing for final ASR transcripts."""

from .edit_tool import (
    DEFAULT_EDIT_MODE,
    EDIT_MODE_FRAGMENT,
    EDIT_MODE_FULL,
    EDIT_MODE_RACE,
    normalize_edit_mode,
)
from .llm import OpenAICompatibleTextProcessor
from .local_server import (
    DEFAULT_LOCAL_BASE_URL,
    DEFAULT_LOCAL_CONTEXT_SIZE,
    DEFAULT_LOCAL_MODEL,
    DEFAULT_LOCAL_MODEL_PATH,
    DEFAULT_LOCAL_REASONING,
    DEFAULT_LOCAL_SERVER_PATH,
    LOCAL_LLM_CATALOG_PATH,
    LOCAL_LLM_HOME_ENV,
    LocalModelServer,
    default_local_llm_home,
    load_local_llm_catalog,
    resolve_default_local_llm,
)
from .model import (
    DEFAULT_ARK_API_KEY_ENV,
    DEFAULT_ARK_BASE_URL,
    DEFAULT_ARK_DEEPSEEK_MODEL,
    DEFAULT_ARK_MODEL,
    INPUT_MODE_DICTATION,
    INPUT_MODE_EDIT,
    INPUT_MODE_INSTRUCTION,
    LLM_PROVIDER_LOCAL,
    LLM_PROVIDER_OPENAI,
    LLM_PROVIDER_VOLCENGINE,
    LLMSettings,
    MAX_EDIT_TARGET_CHARS,
    TextProcessingRequest,
    TextProcessingResult,
    normalize_input_mode,
    normalize_llm_provider,
    validate_edit_target_text,
)
from .worker import TextProcessingWorker

__all__ = [
    "INPUT_MODE_DICTATION",
    "INPUT_MODE_EDIT",
    "INPUT_MODE_INSTRUCTION",
    "DEFAULT_EDIT_MODE",
    "EDIT_MODE_FRAGMENT",
    "EDIT_MODE_FULL",
    "EDIT_MODE_RACE",
    "LLM_PROVIDER_LOCAL",
    "LLM_PROVIDER_OPENAI",
    "LLM_PROVIDER_VOLCENGINE",
    "DEFAULT_ARK_API_KEY_ENV",
    "DEFAULT_ARK_BASE_URL",
    "DEFAULT_ARK_DEEPSEEK_MODEL",
    "DEFAULT_ARK_MODEL",
    "LLMSettings",
    "MAX_EDIT_TARGET_CHARS",
    "DEFAULT_LOCAL_BASE_URL",
    "DEFAULT_LOCAL_CONTEXT_SIZE",
    "DEFAULT_LOCAL_MODEL",
    "DEFAULT_LOCAL_MODEL_PATH",
    "DEFAULT_LOCAL_REASONING",
    "DEFAULT_LOCAL_SERVER_PATH",
    "LOCAL_LLM_CATALOG_PATH",
    "LOCAL_LLM_HOME_ENV",
    "LocalModelServer",
    "default_local_llm_home",
    "load_local_llm_catalog",
    "resolve_default_local_llm",
    "OpenAICompatibleTextProcessor",
    "TextProcessingRequest",
    "TextProcessingResult",
    "TextProcessingWorker",
    "normalize_input_mode",
    "normalize_edit_mode",
    "normalize_llm_provider",
    "validate_edit_target_text",
]
